### ISSUE TITLE
ip_route did not work [1.1.0]

### ISSUE THREAD

**Issue by ufoonline** [vmware/photonos-netmgr#13]
### Describe the bug

OS: photonOS 4.0
netmgr v1.1.0 (Package 1.2.0-3.ph4)

If you try to add a route you will always get 'Invalid parameter' error. 

### Reproduction steps

Assuming eth0 with the following configuration:
IP: 192.168.0.145/24
GW: 192.168.0.254

If you run:
1. netmgr ip_route --add --interface eth0 --gateway 192.168.0.254 --destination 192.168.1.0/24
or
2. netmgr ip_route --add --interface eth0 --gateway 192.168.0.254 --destination 192.168.1.0/24 --metric 1
You will get: 
  ERROR: invalid parameter

### Expected behavior

Add a route under /etc/systemd/network/<interface name>.network and to the routing table.

**Comment by ssahani** [comment]
netmgr is deprecated. Please use https://github.com/vmware/network-config-manager ```nmctl``` . https://github.com/vmware/network-config-manager/blob/master/tests/network-config-manager-tests.py#L636

```tdnf install network-config-manager```

**Comment by ufoonline** [comment]
Thanks a lot, I was using what has been reported in PhotonOS documentation.
I'm gonna move to network-config-manager.
Regards
